[package]
name = "eye"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
quote = "1.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
syn = { version = "1.0", features = ["full", "extra-traits"] }
walkdir = "2.3"
